export type StaticOsintSourceSeed = {
  id: string;
  category: string;
  categoryLabel: string;
  name: string;
  url: string;
  region: string | null;
  reliability: "A" | "B" | "C";
  findingCount: number;
};

// Client-safe copy of the curated BatchOne source catalog from server/osintSeed.ts.
// Keep this in sync with OSINT_SOURCES after applying REMOVED_OSINT_SOURCE_IDS.
export const STATIC_OSINT_SOURCES: StaticOsintSourceSeed[] = [
  {
    id: "osrc-0001",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "NVD CVE API - recent",
    url: "https://services.nvd.nist.gov/rest/json/cves/2.0",
    region: null,
    reliability: "A",
    findingCount: 18,
  },
  {
    id: "osrc-0030",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "CISA KEV - RSS",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    region: null,
    reliability: "A",
    findingCount: 25,
  },
  {
    id: "osrc-0034",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "GitHub Advisory DB (GHSA mirror)",
    url: "https://github.com/github/advisory-database",
    region: null,
    reliability: "A",
    findingCount: 32,
  },
  {
    id: "osrc-0038",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "JVN iPedia - Japan Vulnerability Notes",
    url: "https://jvndb.jvn.jp/en/rss/jvndb.rdf",
    region: "JP",
    reliability: "A",
    findingCount: 39,
  },
  {
    id: "osrc-0039",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "JVN - JPCERT/CC Advisories",
    url: "https://jvn.jp/en/rss/jvn.rdf",
    region: "JP",
    reliability: "A",
    findingCount: 46,
  },
  {
    id: "osrc-0043",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "ZDI - Trend Micro Zero Day Initiative",
    url: "https://www.zerodayinitiative.com/rss/published/",
    region: null,
    reliability: "A",
    findingCount: 53,
  },
  {
    id: "osrc-0044",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "ZDI - Upcoming advisories",
    url: "https://www.zerodayinitiative.com/rss/upcoming/",
    region: null,
    reliability: "A",
    findingCount: 60,
  },
  {
    id: "osrc-0046",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "Tenable Research advisories",
    url: "https://www.tenable.com/security/research/feed",
    region: null,
    reliability: "A",
    findingCount: 67,
  },
  {
    id: "osrc-0508a",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "OSV - PyPI",
    url: "https://osv.dev/list?ecosystem=PyPI",
    region: null,
    reliability: "B",
    findingCount: 21,
  },
  {
    id: "osrc-0032",
    category: "CVE_VULN",
    categoryLabel: "CVE & Vulnerability DBs",
    name: "CIRCL CVE search",
    url: "https://cve.circl.lu/",
    region: null,
    reliability: "A",
    findingCount: 28,
  },
  {
    id: "osrc-0151",
    category: "CERT_GOV",
    categoryLabel: "CERT / Government Advisories",
    name: "NCSC-NL - Netherlands advisories",
    url: "https://advisories.ncsc.nl/rss/advisories",
    region: "NL",
    reliability: "A",
    findingCount: 42,
  },
  {
    id: "osrc-0154",
    category: "CERT_GOV",
    categoryLabel: "CERT / Government Advisories",
    name: "CERT-FR - avis",
    url: "https://www.cert.ssi.gouv.fr/avis/feed/",
    region: "FR",
    reliability: "A",
    findingCount: 49,
  },
  {
    id: "osrc-0159",
    category: "CERT_GOV",
    categoryLabel: "CERT / Government Advisories",
    name: "JPCERT/CC - alerts",
    url: "https://www.jpcert.or.jp/rss/jpcert.rdf",
    region: "JP",
    reliability: "A",
    findingCount: 56,
  },
  {
    id: "osrc-0179",
    category: "CERT_GOV",
    categoryLabel: "CERT / Government Advisories",
    name: "CIRCL - Luxembourg",
    url: "https://circl.lu/rss.xml",
    region: "LU",
    reliability: "A",
    findingCount: 63,
  },
  {
    id: "osrc-0187",
    category: "CERT_GOV",
    categoryLabel: "CERT / Government Advisories",
    name: "NIST - Cybersecurity blog",
    url: "https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",
    region: "US",
    reliability: "A",
    findingCount: 70,
  },
  {
    id: "osrc-0508",
    category: "CERT_GOV",
    categoryLabel: "CERT / Government Advisories",
    name: "Taiwan iThome - Security Weekly",
    url: "https://www.ithome.com.tw/rss",
    region: "TW",
    reliability: "A",
    findingCount: 24,
  },
  {
    id: "osrc-0061",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Palo Alto - Unit 42 threat research",
    url: "https://unit42.paloaltonetworks.com/feed/",
    region: null,
    reliability: "A",
    findingCount: 31,
  },
  {
    id: "osrc-0279",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Microsoft Threat Intelligence",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    region: null,
    reliability: "A",
    findingCount: 45,
  },
  {
    id: "osrc-0277",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "CrowdStrike - Adversary blog",
    url: "https://www.crowdstrike.com/blog/feed/",
    region: null,
    reliability: "A",
    findingCount: 52,
  },
  {
    id: "osrc-0281",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "SentinelLabs",
    url: "https://www.sentinelone.com/labs/feed/",
    region: null,
    reliability: "A",
    findingCount: 59,
  },
  {
    id: "osrc-0282",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "ESET WeLiveSecurity",
    url: "https://feeds.feedburner.com/eset/blog",
    region: null,
    reliability: "A",
    findingCount: 66,
  },
  {
    id: "osrc-0283",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Securelist (Kaspersky)",
    url: "https://securelist.com/feed/",
    region: null,
    reliability: "A",
    findingCount: 27,
  },
  {
    id: "osrc-0289",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "The DFIR Report",
    url: "https://thedfirreport.com/feed/",
    region: null,
    reliability: "A",
    findingCount: 34,
  },
  {
    id: "osrc-0072",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Check Point Research",
    url: "https://research.checkpoint.com/feed/",
    region: null,
    reliability: "A",
    findingCount: 41,
  },
  {
    id: "osrc-0297",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Rapid7 blog",
    url: "https://blog.rapid7.com/rss/",
    region: null,
    reliability: "A",
    findingCount: 48,
  },
  {
    id: "osrc-0304",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Malwarebytes Labs",
    url: "https://www.malwarebytes.com/blog/feed",
    region: null,
    reliability: "B",
    findingCount: 55,
  },
  {
    id: "osrc-0307",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Imperva blog",
    url: "https://www.imperva.com/blog/feed/",
    region: null,
    reliability: "B",
    findingCount: 62,
  },
  {
    id: "osrc-0314",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Bishop Fox",
    url: "https://bishopfox.com/blog/rss.xml",
    region: null,
    reliability: "B",
    findingCount: 69,
  },
  {
    id: "osrc-0348",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "InfoGuard Labs",
    url: "https://labs.infoguard.ch/rss.xml",
    region: "CH",
    reliability: "B",
    findingCount: 23,
  },
  {
    id: "osrc-0058",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Fortinet - PSIRT RSS",
    url: "https://filestore.fortinet.com/fortiguard/rss/ir.xml",
    region: null,
    reliability: "A",
    findingCount: 30,
  },
  {
    id: "osrc-0060",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Palo Alto - PSIRT advisories",
    url: "https://security.paloaltonetworks.com/rss.xml",
    region: null,
    reliability: "A",
    findingCount: 44,
  },
  {
    id: "osrc-0086",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Apple - Security RSS",
    url: "https://developer.apple.com/news/releases/rss/releases.rss",
    region: null,
    reliability: "A",
    findingCount: 51,
  },
  {
    id: "osrc-0087",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Google - Chrome Releases blog",
    url: "https://chromereleases.googleblog.com/feeds/posts/default",
    region: null,
    reliability: "A",
    findingCount: 58,
  },
  {
    id: "osrc-0094",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Ubuntu - Security Notices",
    url: "https://ubuntu.com/security/notices/rss.xml",
    region: null,
    reliability: "A",
    findingCount: 65,
  },
  {
    id: "osrc-0097",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Amazon Linux - Security Advisories",
    url: "https://alas.aws.amazon.com/AL2/alas.rss",
    region: null,
    reliability: "A",
    findingCount: 19,
  },
  {
    id: "osrc-0099",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "AWS - Security Bulletins",
    url: "https://aws.amazon.com/security/security-bulletins/rss/feed/",
    region: null,
    reliability: "A",
    findingCount: 26,
  },
  {
    id: "osrc-0100",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "AWS - Security Blog",
    url: "https://aws.amazon.com/blogs/security/feed/",
    region: null,
    reliability: "A",
    findingCount: 33,
  },
  {
    id: "osrc-0102",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "GCP - Cloud security bulletins",
    url: "https://cloud.google.com/feeds/gcp-release-notes.xml",
    region: null,
    reliability: "A",
    findingCount: 40,
  },
  {
    id: "osrc-0108",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "GitLab - Security blog",
    url: "https://about.gitlab.com/atom.xml",
    region: null,
    reliability: "A",
    findingCount: 47,
  },
  {
    id: "osrc-0135",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Cloudflare - Security blog",
    url: "https://blog.cloudflare.com/tag/security/rss",
    region: null,
    reliability: "A",
    findingCount: 54,
  },
  {
    id: "osrc-0051",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "Microsoft - Azure Security blog",
    url: "https://azure.microsoft.com/en-us/blog/topics/security/feed/",
    region: null,
    reliability: "A",
    findingCount: 61,
  },
  {
    id: "osrc-0339",
    category: "VENDOR_RESEARCH",
    categoryLabel: "Vendor Threat Research",
    name: "CIS - Center for Internet Security",
    url: "https://www.cisecurity.org/feed/",
    region: null,
    reliability: "A",
    findingCount: 68,
  },
  {
    id: "osrc-0263",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "KrebsOnSecurity",
    url: "https://krebsonsecurity.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 22,
  },
  {
    id: "osrc-0264",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "BleepingComputer",
    url: "https://www.bleepingcomputer.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 29,
  },
  {
    id: "osrc-0265",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "The Hacker News",
    url: "https://feeds.feedburner.com/TheHackersNews",
    region: null,
    reliability: "B",
    findingCount: 36,
  },
  {
    id: "osrc-0266",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Dark Reading",
    url: "https://www.darkreading.com/rss.xml",
    region: null,
    reliability: "B",
    findingCount: 43,
  },
  {
    id: "osrc-0269",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "SecurityWeek",
    url: "https://feeds.feedburner.com/Securityweek",
    region: null,
    reliability: "B",
    findingCount: 50,
  },
  {
    id: "osrc-0270",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "The Register - Security",
    url: "https://www.theregister.com/security/headlines.atom",
    region: null,
    reliability: "B",
    findingCount: 57,
  },
  {
    id: "osrc-0318",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Help Net Security",
    url: "https://www.helpnetsecurity.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 64,
  },
  {
    id: "osrc-0319",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "TechCrunch Security",
    url: "https://techcrunch.com/category/security/feed/",
    region: null,
    reliability: "B",
    findingCount: 18,
  },
  {
    id: "osrc-0320",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Wired - Threat Level",
    url: "https://www.wired.com/feed/category/security/latest/rss",
    region: null,
    reliability: "B",
    findingCount: 25,
  },
  {
    id: "osrc-0321",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Infosecurity Magazine UK",
    url: "https://www.infosecurity-magazine.com/rss/news/",
    region: null,
    reliability: "B",
    findingCount: 32,
  },
  {
    id: "osrc-0323",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "CSO Online",
    url: "https://www.csoonline.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 39,
  },
  {
    id: "osrc-0324",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "The Record (Recorded Future)",
    url: "https://therecord.media/feed",
    region: null,
    reliability: "B",
    findingCount: 46,
  },
  {
    id: "osrc-0330",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "NextGov - Cybersecurity",
    url: "https://www.nextgov.com/rss/cybersecurity/",
    region: null,
    reliability: "B",
    findingCount: 53,
  },
  {
    id: "osrc-0331",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Cyberscoop",
    url: "https://www.cyberscoop.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 60,
  },
  {
    id: "osrc-0333",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Schneier on Security",
    url: "https://www.schneier.com/feed/atom/",
    region: null,
    reliability: "B",
    findingCount: 67,
  },
  {
    id: "osrc-0334",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Graham Cluley",
    url: "https://grahamcluley.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 21,
  },
  {
    id: "osrc-0335",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Daniel Miessler",
    url: "https://danielmiessler.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 28,
  },
  {
    id: "osrc-0337",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "SANS ISC Diary",
    url: "https://isc.sans.edu/rssfeed_full.xml",
    region: null,
    reliability: "B",
    findingCount: 35,
  },
  {
    id: "osrc-0341",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Bellingcat",
    url: "https://www.bellingcat.com/feed/",
    region: null,
    reliability: "B",
    findingCount: 49,
  },
  {
    id: "osrc-0342",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "404 Media - Cybersecurity",
    url: "https://www.404media.co/rss",
    region: null,
    reliability: "B",
    findingCount: 56,
  },
  {
    id: "osrc-0344",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "Just Security - Cyber",
    url: "https://www.justsecurity.org/feed/",
    region: null,
    reliability: "B",
    findingCount: 63,
  },
  {
    id: "osrc-0345",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "The Citizen Lab",
    url: "https://citizenlab.ca/feed/",
    region: null,
    reliability: "B",
    findingCount: 70,
  },
  {
    id: "osrc-0347",
    category: "SECURITY_NEWS",
    categoryLabel: "Security News & Press",
    name: "EFF Deeplinks",
    url: "https://www.eff.org/rss/updates.xml",
    region: null,
    reliability: "B",
    findingCount: 24,
  },
  {
    id: "osrc-0258",
    category: "RANSOMWARE_LEAK",
    categoryLabel: "Ransomware & Data-Leak Feeds",
    name: "Ransomware.live - feed",
    url: "https://api.ransomware.live/v2/recentvictims",
    region: null,
    reliability: "B",
    findingCount: 41,
  },
  {
    id: "osrc-0260",
    category: "RANSOMWARE_LEAK",
    categoryLabel: "Ransomware & Data-Leak Feeds",
    name: "DarkFeed - aggregated CTI",
    url: "https://darkfeed.io/feed/",
    region: null,
    reliability: "B",
    findingCount: 48,
  },
  {
    id: "osrc-0261",
    category: "RANSOMWARE_LEAK",
    categoryLabel: "Ransomware & Data-Leak Feeds",
    name: "DataBreaches.net",
    url: "http://feeds.feedburner.com/OfficeOfInadequateSecurity",
    region: null,
    reliability: "B",
    findingCount: 55,
  },
];
